WhatToWear/goods/urls.py
from django.contrib.auth.decorators import permission_required
from .views import GoodListView, GoodDetailView, GoodCreate, GoodUpdate, GoodDelete
from django.contrib import admin
from django.urls import path

urlpatterns = [
    path('', GoodListView.as_view(), name="goods_index"),
    path('<int:pk>/', GoodListView.as_view(), name="goods_index"),
    path('<int:pk>/detail/', GoodDetailView.as_view(), name="goods_detail"),
    path('<int:pk>/add/', permission_required("goods.add_good")(GoodCreate.as_view()), name="goods_add"),
    path('<int:pk>/edit/', permission_required("goods.change_good")(GoodUpdate.as_view()), name="goods_edit"),
    path('<int:pk>/delete/', permission_required("goods.delete_good")(GoodDelete.as_view()), name="goods_delete"),
]

WhatToWear/main/urls.py
from django.urls import path, include
from .views import MainPageView

urlpatterns = [
    path('', MainPageView.as_view(), name="main"),
]

WhatToWear/whattodo/urls.py
from django.contrib import admin
from django.urls import path, include
from django.contrib.auth import views
from django.conf import settings
from django.conf.urls.static import static
from contacts.views import ContactsView


urlpatterns = [
    path('admin/', admin.site.urls),
    path('login/', views.LoginView.as_view(), name="login"),
    path('logout/', views.LogoutView.as_view(), name="logout"),
    path('', include('main.urls')),
    path('news/', include('news.urls')),
    path('imagepool/', include('imagepool.urls')),
    path('categories/', include('categories.urls')),
    path('goods/', include('goods.urls')),
    path('comments/', include('django_comments.urls')),
    path('contacts/', ContactsView.as_view(), name="contacts"),
]

urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

WhatToWear/goods/models.py
from django.db import models
from categories.models import Category
from django.urls import reverse
from easy_thumbnails.files import get_thumbnailer
from django.db.models.signals import pre_delete
from django.dispatch.dispatcher import receiver
from django_comments.models import Comment
from django_comments.moderation import CommentModerator, moderator


class Good(models.Model):
    name = models.CharField(max_length=50, unique=True, db_index=True, verbose_name="Название")
    category = models.ForeignKey(Category, verbose_name="Категория", on_delete=models.CASCADE)
    description = models.TextField(verbose_name="Краткое описание")
    content = models.TextField(verbose_name="Полное описание")
    price = models.FloatField(db_index=True, verbose_name="Цена, руб.")
    price_acc = models.FloatField(null=True, blank=True, verbose_name="Цена с учетом скидки, руб.")
    in_stock = models.BooleanField(default=True, db_index=True, verbose_name="Есть в наличии")
    featured = models.BooleanField(default=False, db_index=True, verbose_name="Рекомендуемый")
    image = models.ImageField(upload_to="goods/list", verbose_name="Основное изображение")

    def save(self, *args, **kwargs):
        try:
            this_record = Good.objects.get(pk=self.pk)
            if this_record.image != self.image:
                thumbnailer = get_thumbnailer(this_record.image)
                thumbnailer.delete_thumbnails()
                this_record.image.delete(save=False)
        except:
            pass
        super(Good, self).save(*args, **kwargs)

    def delete(self, *args, **kwargs):
        thumbnailer = get_thumbnailer(self.image)
        thumbnailer.delete_thumbnails()
        self.image.delete(save=False)
        super(Good, self).delete(*args, **kwargs)

    def get_absolute_url(self):
        return reverse("goods_detail", kwargs={"pk": self.pk})

    class Meta:
        verbose_name = "товар"
        verbose_name_plural = "товары"


class GoodImage(models.Model):
    good = models.ForeignKey(Good, on_delete=models.CASCADE)
    image = models.ImageField(upload_to="goods/detail", verbose_name="Дополнительное изображение")

    def save(self, *args, **kwargs):
        try:
            this_record = GoodImage.objects.get(pk=self.pk)
            if this_record.image != self.image:
                this_record.image.delete(save=False)
        except:
            pass
        super(GoodImage, self).save(*args, **kwargs)

    def delete(self, *args, **kwargs):
        self.image.delete(False)
        super(GoodImage, self).delete(*args, **kwargs)

    def get_absolute_url(self):
        return reverse("goods_detail", kwargs={"pk": self.pk})

    class Meta:
        verbose_name = "изображение к товару"
        verbose_name_plural = "изображения к товару"


@receiver(pre_delete, sender=GoodImage)
def mymodel_delete(sender, instance, **kwargs):
    instance.image.delete(False)


class GoodModerator(CommentModerator):
    email_notification = True


moderator.register(Good, GoodModerator)

WhatToWear/goods/forms.py
from django import forms
from .models import Good


class GoodForm(forms.ModelForm):
    class Meta:
        model = Good
        fields = '__all__'

WhatToWear/goods/views.py
from django.views.generic.base import ContextMixin
from django.views.generic.list import ListView
from .models import Good
from django.views.generic.detail import DetailView
from django.views.generic import TemplateView
from django.forms import inlineformset_factory
from .models import GoodImage
from .forms import GoodForm
from django.contrib import messages
from django.shortcuts import redirect
from django.urls import reverse
from django.views.generic.edit import DeleteView
from categories.models import Category
from generic.controllers import PageNumberView
from generic.mixins import CategoryListMixin, PageNumberMixin


class SortMixin(ContextMixin):
    sort = "0"
    order = "A"

    def get_context_data(self, **kwargs):
        context = super(SortMixin, self).get_context_data(**kwargs)
        context["sort"] = self.sort
        context["order"] = self.order
        return context


class GoodListView(PageNumberView, ListView, SortMixin, CategoryListMixin):
    model = Good
    template_name = "goods_index.html"
    paginate_by = 10
    cat = None

    def get(self, request, *args, **kwargs):
        try:
            if self.kwargs["pk"] is None:
                self.cat = Category.objects.first()
            else:
                self.cat = Category.objects.get(pk=self.kwargs["pk"])
        except KeyError:
            self.cat = Category.objects.first()
        return super(GoodListView, self).get(request, *args, **kwargs)

    def get_context_data(self, **kwargs):
        context = super(GoodListView, self).get_context_data(**kwargs)
        context["category"] = self.cat
        return context

    def get_queryset(self):
        goods = Good.objects.filter(category=self.cat)
        if self.sort == "2":
            if self.order == "D":
                goods = goods.order_by("-in_stock", "name")
            else:
                goods = goods.order_by("in_stock", "name")
        elif self.sort == "1":
            if self.order == "D":
                goods = goods.order_by("-price", "name")
            else:
                goods = goods.order_by("price", "name")

        else:
            if self.order == "D":
                goods = goods.order_by("-name")
            else:
                goods = goods.order_by("name")
        return goods


class GoodDetailView(PageNumberView, DetailView, SortMixin, PageNumberMixin):
    model = Good
    template_name = "good.html"


GoodImagesFormSet = inlineformset_factory(Good, GoodImage, can_order=True, fields='__all__')


class GoodCreate(PageNumberView, TemplateView, SortMixin, PageNumberMixin):
    template_name = "good_add.html"
    cat = None
    form = None
    formset = None

    def get(self, request, *args, **kwargs):
        if self.kwargs["pk"] is None:
            self.cat = Category.objects.first()
        else:
            self.cat = Category.objects.get(pk=self.kwargs["pk"])
        self.form = GoodForm(initial={"category": self.cat})
        self.formset = GoodImagesFormSet()
        return super(GoodCreate, self).get(request, *args, **kwargs)

    def get_context_data(self, **kwargs):
        context = super(GoodCreate, self).get_context_data(**kwargs)
        context["category"] = self.cat
        context["form"] = self.form
        context["formset"] = self.formset
        return context

    def post(self, request, *args, **kwargs):
        self.form = GoodForm(request.POST, request.FILES)
        if self.form.is_valid():
            new_good = self.form.save()
            self.formset = GoodImagesFormSet(request.POST, request.FILES, instance=new_good)
            if self.formset.is_valid():
                self.formset.save()
                messages.add_message(request, messages.SUCCESS, "Товар успешно добавлен")
                return redirect(reverse("goods_index",
                                        kwargs={"pk": new_good.category.pk}) + "?page=" + self.request.GET["page"] +
                                "&sort=" + self.request.GET["sort"] + "&order=" + self.request.GET["order"])
        if self.kwargs["pk"] is None:
            self.cat = Category.objects.first()
        else:
            self.cat = Category.objects.get(pk=self.kwargs["pk"])
        self.formset = GoodImagesFormSet(request.POST, request.FILES)
        return super(GoodCreate, self).get(request, *args, **kwargs)


class GoodUpdate(PageNumberView, TemplateView, SortMixin, PageNumberMixin):
    good = None
    template_name = "good_edit.html"
    form = None
    formset = None

    def get(self, request, *args, **kwargs):
        self.good = Good.objects.get(pk=self.kwargs["pk"])
        self.form = GoodForm(instance=self.good)
        self.formset = GoodImagesFormSet(instance=self.good)
        return super(GoodUpdate, self).get(request, *args, **kwargs)

    def get_context_data(self, **kwargs):
        context = super(GoodUpdate, self).get_context_data(**kwargs)
        context["good"] = self.good
        context["form"] = self.form
        context["formset"] = self.formset
        return context

    def post(self, request, *args, **kwargs):
        self.good = Good.objects.get(pk=self.kwargs["pk"])
        self.form = GoodForm(request.POST, request.FILES, instance=self.good)
        self.formset = GoodImagesFormSet(request.POST, request.FILES, instance=self.good)
        if self.form.is_valid():
            self.form.save()
            if self.formset.is_valid():
                self.formset.save()
                messages.add_message(request, messages.SUCCESS, "Товар успешно изменен")
                return redirect(
                    reverse("goods_index", kwargs={"pk": self.good.category.pk}) + "?page=" + self.request.GET["page"] +
                    "&sort" + self.request.GET["sort"] + "&order=" + self.request.GET["order"])
            return super(GoodUpdate, self).get(request, *args, **kwargs)


class GoodDelete(PageNumberView, DeleteView, SortMixin, PageNumberMixin):
    model = Good
    template_name = "good_delete.html"

    def post(self, request, *args, **kwargs):
        self.success_url = reverse("goods_index", kwargs={"pk": Good.objects.get(pk=kwargs["pk"]).category.pk}) + \
                           "?page=" + self.request.GET["page"] + "&sort=" + self.request.GET["sort"] + "&order=" + \
                           self.request.GET["order"]
        messages.add_message(request, messages.SUCCESS, "Товар успешно удален")
        return super(GoodDelete, self).post(request, *args, **kwargs)

WhatToWear/goods/templates/good.html
{% extends 'main.html' %}
{% load comments %}
{% block title %}{{ object.name }} :: {{ object.category.name }}
{% endblock %}
{% block main %}
    <h2>{{ object.name }}</h2>
    <p>Категория: {{ object.category.name }}</p>
    <div class="good-images">
        <div><img src="{{ object.image.url }}"></div>
        {% for goodimage in object.goodimage_set.all %}
            <div><img src="{{ goodimage.image.url }}"></div>
        {% endfor %}
    </div>
    <div>{{ object.content }}</div>
    <p>Цена, руб.: {% if object.price_acc > 0 %}<span class="old-price">
        {{ object.price }}</span>&nbsp;{{ object.price_acc }}{% else %}
        {{ object.price }}{% endif %}</p>
        {% if object.in_stock %}
            <p>В наличии.</p>
        {% else %}
            <p>Нет наличии.</p>
        {% endif %}
    <p><a href="{% url 'goods_index' pk=object.category.pk %}?page={{ pn }}&sort={{ sort }}&order={{ order }}">Назад</a></p>
    <p>&nbsp;</p>
    {% render_comment_list for object %}
    <p>&nbsp;</p>
    {% get_comment_form for object as form %}
    <div class="form">
        <form action="{% comment_form_target %}" method="post">
            {% include "generic/form.html" %}
            <input type="hidden" name="next" value="{% url 'goods_detail' pk=object.pk %}?page={{ pn }}&sort={{ sort }}&order={{ order }}">
            <div class="submit-button">
                <input type="submit" name="submit" value="Отправить">
            </div>
        </form>
    </div>
{% endblock %}

WhatToWear/goods/templates/good_add.html
{% extends "main.html" %}
{% block title %}Добавление товара :: {{ category.name }}{% endblock %}
{% block main %}
    <h2>Добавление товара</h2>
    <div class="form">
        <form action="" method="post" enctype="multipart/form-data">
            {% include 'generic/form.html' %}
            {% include 'generic/formset.html' %}
            <div class="submit-button"><input type="submit" value="Добавить"></div>
        </form>
    </div>
    <p><a href="{% url 'goods_index' pk=category.pk %}
    ?page={{ pn }}&sort={{ sort }}&order={{ order }}">Назад</a></p>
{% endblock %}

WhatToWear/goods/templates/good_delete.html
{% extends "main.html" %}
{% block title %}Удаление товара :: {{ object.name }}{% endblock %}
{% block main %}
    <h2>Удаление товара</h2>
    <h4>{{ object.name }}</h4>
    <p>Категория: {{ object.category.name }}</p>
    <div>{{ object.content|bbcode|safe }}</div>
    <p>Цена, руб.: {% if object.price_acc > 0 %}<span class="old-price">
        {{ object.price }}</span>&nbsp;&nbsp;{{ object.price_acc }}{% else %}
        {{ object.price }}{% endif %}
    </p>
    {% if object.in_stock %}
        <p>Нет в наличии.</p>
    {% endif %}
    {% if object.featured %}
        <p>Рекомендуемый.</p>
    {% endif %}
    <form action="" method="post">
        {% csrf_token %}
        <input type="submit" value="Удалить">
    </form>
    <p><a href="{% url 'goods_index' pk=object.category.pk %}?page={{ pn }}&sort={{ sort }}&order={{ order }}">Назад</a></p>
{% endblock %}

WhatToWear/goods/templates/good_edit.html
{% extends "main.html" %}
{% block title %}Правка товара :: {{ good.name }}{% endblock %}
{% block main %}
    <h2>Правка товара</h2>
    <div class="form">
        <form action="" method="post" enctype="multipart/form-data">
            {% include 'generic/form.html' %}
            {% include 'generic/formset.html' %}
            <div class="submit-button"><input type="submit" value="Изменить"></div>
        </form>
    </div>
    <p><a href="{% url 'goods_index' pk=good.category.pk %}?page={{ pn }}&sort={{ sort }}&order={{ order }}">Назад</a></p>
{% endblock %}

WhatToWear/goods/templates/goods_index.html
{% extends "main.html" %}
{% load thumbnail %}

{% block title %}{{ category.name }}{% endblock %}
{% block main %}
    {% include "generic/messages.html" %}
    <h2>{{ category.name }}</h2>
    {% if perms.goods.add_good %}
        <p><a href="{% url 'goods_add' pk=category.pk %}?page={{ page_obj.number }}&sort={{ sort }}&order={{ order }}">Добавить товар</a></p>
    {% endif %}
    <table class="list-table">
        <tr>
            <th>Миниатюра</th>
            <th>
                <a href="?sort=0&order={% if sort == '0' and order == 'A' %}D{% else %}A{% endif %}">
                    {% if sort == "0" %}{% if order == "D" %}&#9660;{% else %}&#9650;{% endif %}{% endif %}&nbsp;Название
                </a>
            </th>
            <th>Описание</th>
            <th>
                <a href="?sort=1&order={% if sort == '1' and order == 'A' %}D{% else %}A{% endif %}">
                    {% if sort == "1" %}{% if order == "D" %}&#9660;{% else %}&#9650;{% endif %}{% endif %}&nbsp;Цена, руб.
                </a>
            </th>
            <th>
                <a href="?sort=2&order={% if sort == '2' and order == 'A' %}D{% else %}A{% endif %}">
                    {% if sort == "2" %}{% if order == "D" %}&#9660;{% else %}&#9650;{% endif %}{% endif %}&nbsp;В продаже
                </a>
            </th>
            {% if perms.goods.change_good %}
                <th>&nbsp;</th>
            {% endif %}
            {% if perms.goods.delete_good %}
                <th>&nbsp;</th>
            {% endif %}
        </tr>
        {% for object in object_list %}
            <tr>
                <td class="centered"><a href="{% url 'goods_detail' pk=object.pk %}?page={{ page_obj.number }}&sort={{ sort }}&order={{ order }}"><img src="{% thumbnail object.image 'base' %}"></a></td>
                <td><a href="{% url 'goods_detail' pk=object.pk %}?page={{ page_obj.number }}&sort={{ sort }}&order={{ order }}">{{ object.name }}</a></td>
                <td>{{ object.description }}</td>
                <td class="centered">
                    {% if object.price_acc > 0 %}
                        <span class="old-price">{{ object.price }}</span><br>
                        {{ object.price_acc }}
                    {% else %}{{ object.price }}
                    {% endif %}
                </td>
                <td class="centered">
                    {% if object.in_stock %}+
                    {% else %}-
                    {% endif %}
                </td>
                {% if perms.page.change_good %}
                    <td class="centered"><a href="{% url 'goods_edit' pk=object.pk %}?page={{ page_obj.number }}&sort={{ sort }}&order={{ order }}">Изменять</a></td>
                {% endif %}
                {% if perms.page.delete_good %}
                    <td class="centered"><a href="{% url 'goods_delete' pk=object.pk %}?page={{ page_obj.number }}&sort={{ sort }}&order={{ order }}">Удалить</a></td>
                {% endif %}
            </tr>
        {% endfor %}
    </table>
    {% include "generic/pagination.html" %}
{% endblock %}

WhatToWear/goods/templates/list.html
{% if comments_list|length > 0 %}
    <p>&nbsp;</p>
    {% for comment in comment_list %}
        {% if comment.is_removed %}
            <p class="comment-removed">Комментарий удален.</p>
        {% else %}
            <div class="comment">
                <div class="user">{{ comment.user_name }}</div>
                <div class="content">{{ comment.comment }}</div>
                <div class="date">{{ comment.submit_date|date:"j.m.Y H:i:s" }}</div>
            </div>
        {% endif %}
    {% endfor %}
{% endif %}